"use client";

import { useMemo, useState } from "react";

type Product = { id: number; name: string; price: number; category: string; note: string; image: string; };
const products: Product[] = [
  { id: 1, name: "The Marigold", price: 74, category: "Seasonal", note: "Dahlia, ranunculus, garden rose", image: "https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=1000&q=85" },
  { id: 2, name: "Quiet Morning", price: 62, category: "Everyday", note: "Tulip, sweet pea, chamomile", image: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1000&q=85" },
  { id: 3, name: "Afterglow", price: 86, category: "Seasonal", note: "Apricot rose, cosmos, snapdragon", image: "https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1000&q=85" },
  { id: 4, name: "The Conservatory", price: 98, category: "Statement", note: "Orchid, anthurium, sculptural greens", image: "https://images.unsplash.com/photo-1487070183336-b863922373d4?auto=format&fit=crop&w=1000&q=85" },
  { id: 5, name: "Sunday Table", price: 118, category: "Statement", note: "A lush centerpiece for gathering", image: "https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?auto=format&fit=crop&w=1000&q=85" },
  { id: 6, name: "Petite Merci", price: 48, category: "Everyday", note: "A small, joyful thank-you", image: "https://images.unsplash.com/photo-1487530811176-3780de880c2d?auto=format&fit=crop&w=1000&q=85" },
];
const fmt = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export default function Home() {
  const [filter, setFilter] = useState("All"); const [cart, setCart] = useState<Product[]>([]); const [open, setOpen] = useState(false);
  const [delivery, setDelivery] = useState("Today"); const [size, setSize] = useState("Gathered"); const [palette, setPalette] = useState("Soft & romantic");
  const list = useMemo(() => filter === "All" ? products : products.filter(p => p.category === filter), [filter]);
  const add = (p: Product) => { setCart(c => [...c, p]); setOpen(true); };
  const checkout = async () => {
    const response = await fetch("/api/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: cart }) });
    const data = await response.json(); if (data.url) window.location.href = data.url; else alert(data.error || "Add your Stripe key to enable checkout.");
  };
  return <main>
    <header className="nav"><a className="brand" href="#top"><span>✦</span> LINDEN <i>&</i> BLOOM</a><nav><a href="#shop">Shop</a><a href="#custom">Custom flowers</a><a href="#story">Our story</a></nav><button className="bag" onClick={() => setOpen(true)}>Bag <b>{cart.length}</b></button></header>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">CHICAGO · EST. 2017</p><h1>Flowers for the <em>beautiful</em> everyday.</h1><p className="intro">Seasonal, garden-inspired flowers arranged with a little wildness and a lot of heart.</p><a className="button cream" href="#shop">Shop today&apos;s flowers <span>→</span></a><p className="delivery-dot"><b>●</b> Same-day delivery available until 1 PM</p></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=1400&q=90" alt="Colorful seasonal flower arrangement" /></div><div className="stamp">made<br/>with<br/>feeling</div></section>
    <section className="promise"><p>Thoughtfully sourced</p><span>✦</span><p>Hand-arranged in Chicago</p><span>✦</span><p>Delivered with care</p></section>
    <section className="shop section" id="shop"><div className="section-top"><div><p className="eyebrow">THE FLOWER SHOP</p><h2>This week&apos;s <em>favourites.</em></h2></div><div className="filters">{["All", "Seasonal", "Everyday", "Statement"].map(x => <button className={filter === x ? "active" : ""} onClick={() => setFilter(x)} key={x}>{x}</button>)}</div></div><div className="grid">{list.map(p => <article className="product" key={p.id}><div className="product-img"><img src={p.image} alt={p.name} /><button onClick={() => add(p)}>Add to bag <span>+</span></button></div><div className="product-info"><div><h3>{p.name}</h3><p>{p.note}</p></div><strong>{fmt.format(p.price)}</strong></div></article>)}</div><a className="text-link" href="#shop">Explore all arrangements <span>→</span></a></section>
    <section className="builder" id="custom"><div className="builder-photo"><img src="https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=1100&q=85" alt="Florist selecting flowers" /></div><div className="builder-copy"><p className="eyebrow">OUR SIGNATURE SERVICE</p><h2>Make it<br/><em>yours.</em></h2><p>Tell us the feeling. We&apos;ll make the flowers. Every custom bouquet is made from the season&apos;s best stems.</p><div className="choices"><label>Palette<select value={palette} onChange={e => setPalette(e.target.value)}><option>Soft & romantic</option><option>Bright & joyful</option><option>Earthy & wild</option></select></label><label>Size<div className="pills">{["Petite", "Gathered", "Grand"].map(s => <button className={size === s ? "selected" : ""} onClick={() => setSize(s)} key={s}>{s}</button>)}</div></label></div><button className="button dark" onClick={() => add({ id: 99, name: `Custom — ${size}`, price: size === "Petite" ? 58 : size === "Grand" ? 125 : 82, category: "Custom", note: palette, image: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1000&q=85" })}>Create your bouquet <span>→</span></button></div></section>
    <section className="delivery section"><div><p className="eyebrow">FLOWERS, RIGHT ON TIME</p><h2>Need them <em>today?</em></h2><p>Our neighborhood couriers make same-day deliveries across Chicago, seven days a week.</p><a className="text-link" href="#shop">See delivery details <span>→</span></a></div><div className="date-card"><p>WHEN SHOULD WE DELIVER?</p><div className="dates">{["Today", "Tomorrow", "Fri, Jun 27"].map((d, i) => <button className={delivery === d ? "date-selected" : ""} onClick={() => setDelivery(d)} key={d}><small>{i === 0 ? "WED" : i === 1 ? "THU" : "FRI"}</small><b>{i + 25}</b><span>{d}</span></button>)}</div><div className="time"><span>Available time</span><b>{delivery === "Today" ? "2:00 – 6:00 PM" : "9:00 AM – 1:00 PM"}</b></div></div></section>
    <section className="quote"><p>“The kind of flower shop that makes an ordinary Tuesday feel like an occasion.”</p><span>— CHICAGO MAGAZINE</span></section>
    <section className="story" id="story"><img src="https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=1100&q=85" alt="Bunches of flowers" /><div><p className="eyebrow">OUR CORNER OF CHICAGO</p><h2>Come say <em>hello.</em></h2><p>Find us in a sun-filled storefront in Logan Square, where the coffee is strong and the flower buckets are always full.</p><p><b>1842 N. Milwaukee Ave.</b><br/>Chicago, Illinois 60647</p><p><b>Tuesday–Saturday</b><br/>9 AM–6 PM · Sunday 10 AM–3 PM</p><a className="text-link" href="mailto:hello@lindenandbloom.com">Get in touch <span>→</span></a></div></section>
    <footer><div className="brand">✦ LINDEN <i>&</i> BLOOM</div><p>Flowers, thoughtfully arranged.</p><div><a href="#shop">Instagram</a><a href="#shop">Pinterest</a><a href="mailto:hello@lindenandbloom.com">Email</a></div><small>© 2026 Linden & Bloom</small></footer>
    {open && <aside className="cart"><div className="cart-head"><h2>Your bag <em>({cart.length})</em></h2><button onClick={() => setOpen(false)}>×</button></div>{cart.length ? <><div className="cart-items">{cart.map((p, i) => <div className="cart-item" key={`${p.id}-${i}`}><img src={p.image} alt=""/><div><b>{p.name}</b><p>{p.note}</p><strong>{fmt.format(p.price)}</strong></div><button onClick={() => setCart(c => c.filter((_, index) => index !== i))}>×</button></div>)}</div><div className="cart-footer"><div><span>Subtotal</span><b>{fmt.format(cart.reduce((n, p) => n + p.price, 0))}</b></div><button className="button dark" onClick={checkout}>Secure checkout <span>→</span></button><small>Delivery time is selected at checkout.</small></div></> : <div className="empty">Your bag is waiting for something lovely.<a href="#shop" onClick={() => setOpen(false)}>Shop flowers →</a></div>}</aside>}
    {open && <div className="scrim" onClick={() => setOpen(false)} />}
  </main>;
}
